name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3
        with:
          cache: false
      - run: mise run test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
